---
version: "3.9"
services:
  app1:
    build: "./javaee-example-app1"
    networks:
      - "example"
    ports:
      - "8080:8080"
  app2:
    build: "./javaee-example-app2"
    networks:
      - "example"
    ports:
      - "8081:8080"
  keycloak:
    image: "jboss/keycloak:16.1.0"
    environment:
      DB_ADDR: "mariadb"
      DB_VENDOR: "mariadb"
      DB_PASSWORD: "keycloak"
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
    ports:
      - "8082:8080"
    networks:
      - "example"
  mariadb:
    image: "mariadb:10.3.32"
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - "./keycloak-db-setup.sql:/docker-entrypoint-initdb.d/keycloak-db-setup.sql"
      - "db-data:/var/lib/mysql"
    networks:
      - "example"

volumes:
  db-data:

networks:
  example: