FROM jboss/wildfly:25.0.0.Final
#ADD ./javeee-example-app1/target/javaee-example-app1-1.0.0-SNAPSHOT.war /opt/jboss/wildfly/standalone/deployments/app1.war
ADD ./target/javaee-example-app1-1.0.0-SNAPSHOT.war /opt/jboss/wildfly/standalone/deployments/app1.war
